# Generated by Django 5.2.7 on 2025-12-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, help_text="Введите вашу страну", max_length=30, null=True, verbose_name="Страна"
            ),
        ),
    ]
