# Generated by Django 5.2.7 on 2025-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Введите заголовок", max_length=100, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите текст", max_length=10000, null=True, verbose_name="Содержимое"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, help_text="Загрузите превью", null=True, upload_to="blog/photo"),
                ),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=True)),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
