# Generated by Django 5.2.7 on 2025-12-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(
                blank=True, help_text="Введите текст", max_length=10000, null=True, verbose_name="Содержимое"
            ),
        ),
    ]
