# Generated by Django 5.2.7 on 2025-10-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите наименование", max_length=100, verbose_name="Наименование"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание", max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите наименование", max_length=100, verbose_name="Наименование"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание", max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, help_text="Загрузите фото", null=True, upload_to="Product/photo"),
                ),
                (
                    "category",
                    models.CharField(help_text="Введите категорию", max_length=100, verbose_name="Категория"),
                ),
                ("price", models.IntegerField(help_text="Введите цену", verbose_name="Цена")),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("updated_at", models.DateField(verbose_name="Дата последнего изменения")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "category", "price"],
            },
        ),
    ]
