# Generated by Django 5.2.7 on 2025-12-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите наименование", max_length=100, verbose_name="Наименование"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание", max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите наименование", max_length=100, verbose_name="Наименование"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание", max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, help_text="Загрузите фото", null=True, upload_to="products/photo"),
                ),
                ("price", models.IntegerField(help_text="Введите цену", verbose_name="Цена")),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                ("updated_at", models.DateField(verbose_name="Дата последнего изменения")),
                ("is_published", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите категорию",
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "category", "price"],
            },
        ),
    ]
