# Generated by Django 5.2.7 on 2025-12-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price"],
                "permissions": [
                    ("can_edit_name", "Can edit name"),
                    ("can_edit_description", "Can edit description"),
                    ("can_unpublish_product", "Can unpublish product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
