# Generated by Django 5.2.7 on 2025-12-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options_product_delete_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="views_counter",
        ),
    ]
